[[hook]]
prefix = "/hermes1/status/hooks"
links = ["http://127.0.0.1:9999/status-update", "http://127.0.0.1:9999/status-update-2"]

[[hook]]
prefix = "/hermes1/agent/hooks"
links = ["http://127.0.0.1:9999/agent-update"]

[[record]]
key = "/hermes1/status/server1"
value = "online"

[[record]]
key = "/hermes1/status/server2"
value = "offline"
