[network]
classic = "0.0.0.0:3030"     # Classic TCP interface bind to this address
rest = "0.0.0.0:3032"        # REST interface bind to this address
websocket = "0.0.0.0:3033"   # REST interface bind to this address

[initials]
# Records and hooks will be read from here during startup
path = "/usr/var/hermes/init.toml"

[logger]
location = "/usr/var/hermes/log.txt" # Which file should the database log written

[scripts]
lib_path = "/usr/var/hermes/lua/libs"
exec_path = "/usr/var/hermes/lua"
execs = [
    "test.lua",
    "work_with_words.lua",
    "simple_words.lua",
    "error_example.lua",
]