[network]
classic = "127.0.0.1:3030"     # Classic TCP interface bind to this address
grpc = "127.0.0.1:3031"        # gRPC interface bind to this address
rest = "127.0.0.1:3032"        # REST interface bind to this address
websocket = "127.0.0.1:3033"   # Websocket interface bind to this address

[initials]
# Records and hooks will be read from here during startup
path = "/home/ati/work/OnlyAti.Hermes/hermes/init_data.toml"

[logger]
location = "/tmp/hermes-datastore-test.txt" # Which file should the database log written

[scripts]
lib_path = "./lua-examples/libs"
exec_path = "./lua-examples"
execs = [
    "test.lua",
    "work_with_words.lua",
    "simple_words.lua",
    "error_example.lua",
]
