[network]
classic = "127.0.0.1:3031"     # Classic TCP interface bind to this address
rest = "0.0.0.0:3032"        # REST interface bind to this address
websocket = "127.0.0.1:3033"   # Websocket interface bind to this address

[initials]
# Records and hooks will be read from here during startup
path = "/home/ati/work/OnlyAti.Hermes/hermes/init_data.toml"

[logger]
mem_only = false
location = "/tmp/hermes-datastore-test" # Directory for logs

[scripts]
lib_path = "./lua-examples/libs"
exec_path = "./lua-examples"
execs = [
    "test.lua",
    "work_with_words.lua",
    "simple_words.lua",
    "error_example.lua",
]

[gitea]
enable = true
script = "gitea_parser.lua"
key_base = "/root/gitea"
