[[record]]
key = "/hermes1/test1"
value = "This is a value"
override = true

[[record]]
key = "/hermes1/test2"
value = "This is another value"

[[record]]
key = "/hermes1/status/server1"
value = "online"

[[record]]
key = "/hermes1/status/server2"
value = "online"

[[record]]
key = "/hermes1/status/server3"
value = "offline"

[[record]]
key = "/hermes1/status/server4"
value = "online"

[[record]]
key = "/hermes1/status/proxy"
value = "online"

[[hook]]
prefix = "/hermes1/arpa"
links = [ "http://127.0.0.1:9999/getone", "http://127.0.0.1:9999/getanotherone" ]

[[hook]]
prefix = "/hermes1/another"
links = [ "http://127.0.0.1:9999/whatis" ]

